In [1]:
import pandas as pd
import constants

In [2]:
# Data frames
website_frame = pd.read_csv(constants.CSV_SOURCE_URL)
fixtures_frame = pd.read_csv("../../dataset/2024-2025 fixtures.csv")

In [3]:
fixtures_frame.head()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
0,1,1,16/08/2024 20:00,Old Trafford,Man Utd,Fulham,1 - 0
1,2,1,17/08/2024 12:30,Portman Road,Ipswich,Liverpool,0 - 2
2,3,1,17/08/2024 15:00,Emirates Stadium,Arsenal,Wolves,2 - 0
3,4,1,17/08/2024 15:00,Goodison Park,Everton,Brighton,0 - 3
4,5,1,17/08/2024 15:00,St. James' Park,Newcastle,Southampton,1 - 0

In [4]:
import numpy as np

fixture_teams = fixtures_frame["Home Team"].unique()
website_teams = website_frame["HomeTeam"].unique()

# Teams in fixture_teams but not in website_teams
diff_fixture_to_website = np.setdiff1d(fixture_teams, website_teams)

# Teams in website_teams but not in fixture_teams
diff_website_to_fixture = np.setdiff1d(website_teams, fixture_teams)

print("In fixture_teams but not in website_teams:", diff_fixture_to_website)
print("In website_teams but not in fixture_teams:", diff_website_to_fixture)

In fixture_teams but not in website_teams: ['Man Utd' 'Spurs']
In website_teams but not in fixture_teams: ['Man United' 'Tottenham']

In [5]:
# Standardize names from website to fixtures for both home and away teams
mapping = {'Man Utd': 'Man United', 'Spurs': 'Tottenham'}
fixtures_frame["Home Team"] = fixtures_frame["Home Team"].replace(mapping)
fixtures_frame["Away Team"] = fixtures_frame["Away Team"].replace(mapping)

In [6]:
fixtures_frame.insert(0, "MatchID", constants.CURRENT_SEASON_TAG + "_" + fixtures_frame["Home Team"] + "_" + fixtures_frame["Away Team"])

In [7]:
fixtures_frame.head(20)

,MatchID,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
0,2024-2025_Man United_Fulham,1,1,16/08/2024 20:00,Old Trafford,Man United,Fulham,1 - 0
1,2024-2025_Ipswich_Liverpool,2,1,17/08/2024 12:30,Portman Road,Ipswich,Liverpool,0 - 2
2,2024-2025_Arsenal_Wolves,3,1,17/08/2024 15:00,Emirates Stadium,Arsenal,Wolves,2 - 0
3,2024-2025_Everton_Brighton,4,1,17/08/2024 15:00,Goodison Park,Everton,Brighton,0 - 3
4,2024-2025_Newcastle_Southampton,5,1,17/08/2024 15:00,St. James' Park,Newcastle,Southampton,1 - 0
5,2024-2025_Nott'm Forest_Bournemouth,6,1,17/08/2024 15:00,The City Ground,Nott'm Forest,Bournemouth,1 - 1
6,2024-2025_West Ham_Aston Villa,7,1,17/08/2024 17:30,London Stadium,West Ham,Aston Villa,1 - 2
7,2024-2025_Brentford_Crystal Palace,8,1,18/08/2024 14:00,Gtech Community Stadium,Brentford,Crystal Palace,2 - 1
8,2024-2025_Chelsea_Man City,9,1,18/08/2024 16:30,Stamford Bridge,Chelsea,Man City,0 - 2
9,2024-2025_Leicester_Tottenham,10,1,19/08/2024 20:00,King Power Stadium,Leicester,Tottenham,1 - 1
10,2024-2025_Brighton_Man United,13,2,24/08/2024 12:30,American Express Stadium,Brighton,Man United,2 - 1
11,2024-2025_Crystal Palace_West Ham,14,2,24/08/2024 15:00,Selhurst Park,Crystal Palace,West Ham,0 - 2
12,2024-2025_Fulham_Leicester,15,2,24/08/2024 15:00,Craven Cottage,Fulham,Leicester,2 - 1
13,2024-2025_Man City_Ipswich,17,2,24/08/2024 15:00,Etihad Stadium,Man City,Ipswich,4 - 1
14,2024-2025_Southampton_Nott'm Forest,18,2,24/08/2024 15:00,St. Mary's Stadium,Southampton,Nott'm Forest,0 - 1
15,2024-2025_Tottenham_Everton,19,2,24/08/2024 15:00,Tottenham Hotspur Stadium,Tottenham,Everton,4 - 0
16,2024-2025_Aston Villa_Arsenal,11,2,24/08/2024 17:30,Villa Park,Aston Villa,Arsenal,0 - 2
17,2024-2025_Bournemouth_Newcastle,12,2,25/08/2024 14:00,Vitality Stadium,Bournemouth,Newcastle,1 - 1
18,2024-2025_Wolves_Chelsea,20,2,25/08/2024 14:00,Molineux Stadium,Wolves,Chelsea,2 - 6
19,2024-2025_Liverpool_Brentford,16,2,25/08/2024 16:30,Anfield,Liverpool,Brentford,2 - 0

In [8]:
fixtures_frame = fixtures_frame[["MatchID", "Round Number", "Date"]]

In [9]:
fixtures_frame.to_csv("../../dataset/2024-2025 fixtures processed.csv", index=False)
# Save the updated fixtures frame